#!/bin/bash

cd src

echo "Clean porousforce..."
(cd porousforce && wclean)

echo "Clean porousolaFlow..."
(cd porousolaFlow && wclean)

echo "Clean porousolaFlow..."
(cd poroussixDoFRigidBodyMotion && wclean)
