#!/bin/bash

wclean all > /dev/null

wmake all

if (( $? )) ; then 
    echo "olaFlow solvers compilation failed"
    exit; else
    echo -e "\n\nolaFlow solvers compiled successfully for $WM_PROJECT $WM_PROJECT_VERSION\n\n\n";

    # Create symbolic link if olaDyMFlow does not exist (OF-dev, OFv1806)
    if [ ! -f $FOAM_USER_APPBIN/porousolaDyMFlow ]; then
        ln -s $FOAM_USER_APPBIN/porousolaFlow $FOAM_USER_APPBIN/porousolaDyMFlow
    fi
fi

wclean all > /dev/null
