#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


rm ./system/decomposeParDict
cp ./system/decomposeParDict_solver ./system/decomposeParDict
nProc=$(getNumberOfProcessors)
runApplication decomposePar

nProc=$(getNumberOfProcessors)
solver="mpirun -np $nProc olaFlow -parallel"

runApplication $solver
mv log.mpirun log.olaFlow


echo reconstruct...
reconstructPar

#rm -r processor*

echo Simulation complete.
