#!/bin/bash
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf constant/polyMesh/sets
rm -f log.topoSet* log.postProcess*

# 确保使用的是更新后的 19x8 topoSetDict
cp ./system/topoSetDict_Big ./system/topoSetDict

echo "1. Generating 19x8 cellSets on reconstructed mesh..."
runApplication topoSet
mv log.topoSet log.topoSet_Big

echo "2. Running postProcess using flowAve_Big dictionary..."
# 使用 -dict 参数指定执行 system/flowAve_Big 文件里的 functions
# 如果你只想提取最新时间步，可以在后面加上 -latestTime
olaFlow -postProcess -dict system/flowAve_Big -time 18.9:50
mv log.postProcess log.postProcess_flowAve_Big

echo "Extraction complete. Please check the postProcessing directory."
