#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -r 0
rm -r processor*
rm log.setFields
rm log.decomposePar
rm log.mpirun
rm log.topoSet
rm log.createPatch

restore0Dir


runApplication topoSet
runApplication createPatch -overwrite
runApplication setFields


#rm ./system/blockMeshDict
#cp ./system/blockMeshDict_cyclic ./system/blockMeshDict

rm ./system/decomposeParDict
cp ./system/decomposeParDict_solver ./system/decomposeParDict
nProc=$(getNumberOfProcessors)
runApplication decomposePar

renumber_application="mpirun -np $nProc renumberMesh -overwrite -parallel"
runApplication $renumber_application
mv log.mpirun log.renumberMesh

nProc=$(getNumberOfProcessors)
solver="mpirun -np $nProc olaFlow -parallel"

#mpirun -np 60 olaFlow -parallel > log.olaFlow

runApplication $solver
mv log.mpirun log.olaFlow


echo reconstruct...
reconstructPar

#rm -r processor*

echo Simulation complete.
