#!/bin/bash
shopt -s extglob

directory=`pwd`

if [ -d "./constant/polyMesh" ]; then
  cd ./constant/polyMesh
  rm -fr !(blockMeshDict)
  cd $directory
fi

rm -fr *[0-9].[0-9]* [0-9] [1-9]* dynamicCode
rm log.*
rm -rf postProcessing
rm -rf processor*


cd Mooring
rm -rf VTK
rm *.out
rm restart*
rm *.ic
rm -rf boxWu_exPoint

