#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# 1. 清理工作
echo "Cleaning up..."
rm -r 0
rm -r processor*
rm log.*
rm -r postPro*

# 2. 恢复 0 文件夹
restore0Dir

# ==============================================================
# 网格备份与恢复模块
# 作用：保证每次运行脚本时，polyMesh 都是初始状态
# ==============================================================
if [ -d "constant/polyMesh.orig" ]; then
    echo "Backup found. Restoring original mesh from constant/polyMesh.orig..."
    # 如果备份存在，说明之前运行过。先删掉当前被修改过的网格，把备份还原回来。
    rm -rf constant/polyMesh
    cp -r constant/polyMesh.orig constant/polyMesh
else
    echo "No backup found. Creating backup to constant/polyMesh.orig..."
    # 如果备份不存在，说明这是第一次运行（或者是刚画好网格）。立即创建一个备份。
    cp -r constant/polyMesh constant/polyMesh.orig
fi
# ==============================================================


# 3. 第一轮 topoSet (为了 createPatch 选面)
echo "Running topoSet for patch creation..."
rm ./system/topoSetDict
cp ./system/topoSetDict_A ./system/topoSetDict
runApplication topoSet
mv log.topoSet log.topoSet1

# 4. 创建边界 (这一步会永久修改 constant/polyMesh，但我们上面已经有备份了，不怕)
echo "Running createPatch..."
runApplication createPatch -overwrite

# 5. 初始化场
echo "Running setFields..."
runApplication setFields

# 6. 第二轮 topoSet (关键步骤：重新生成因 createPatch 而丢失的 cellSet)
echo "Running topoSet for cell zones..."
rm ./system/topoSetDict
cp ./system/topoSetDict_B ./system/topoSetDict
runApplication topoSet
mv log.topoSet log.topoSet2

# 7. 准备分块
echo "Decomposing domain..."
rm ./system/decomposeParDict
cp ./system/decomposeParDict_solver ./system/decomposeParDict
nProc=$(getNumberOfProcessors)
# 加上 -force 确保新的 cellSet 被分发
runApplication decomposePar -force

# renumberMesh (如果以后要用，确保放在 decomposePar 之前，且记得用完后再运行一次 topoSet)
#renumber_application="mpirun -np $nProc renumberMesh -overwrite -parallel"
#runApplication $renumber_application
#mv log.mpirun log.renumberMesh

# 8. 运行求解器
echo "Running solver..."
nProc=$(getNumberOfProcessors)
solver="mpirun -np $nProc olaFlow -parallel"

#mpirun -np 60 olaFlow -parallel > log.olaFlow

runApplication $solver
mv log.mpirun log.olaFlow

# 9. 重建场
echo "Reconstructing..."
reconstructPar

#rm -r processor*

echo "Simulation complete."
